--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/crogers/Pictures/walls/91392352_p0_master1200.jpg"

-- Special
background="#1f2c37"
foreground="#c6c6c7"
cursor="#c6c6c7"

-- Colors
color0="#1f2c37"
color1="#2d8bb7"
color2="#3fa2cf"
color3="#54abd4"
color4="#55bad4"
color5="#e39192"
color6="#8cdae2"
color7="#c6c6c7"
color8="#545557"
color9="#2d8bb7"
color10="#3fa2cf"
color11="#54abd4"
color12="#55bad4"
color13="#e39192"
color14="#8cdae2"
color15="#c6c6c7"
