# Shell variables
# Generated by 'wal'
wallpaper='/home/crogers/Pictures/walls/91392352_p0_master1200.jpg'

# Special
background='#1f2c37'
foreground='#c6c6c7'
cursor='#c6c6c7'

# Colors
color0='#1f2c37'
color1='#2d8bb7'
color2='#3fa2cf'
color3='#54abd4'
color4='#55bad4'
color5='#e39192'
color6='#8cdae2'
color7='#c6c6c7'
color8='#545557'
color9='#2d8bb7'
color10='#3fa2cf'
color11='#54abd4'
color12='#55bad4'
color13='#e39192'
color14='#8cdae2'
color15='#c6c6c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
